// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `audience_keys`, `key`, `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `fmt`, `from`, `from`, `try_from`

/// Encrypts [payload] into [object]'s slot, readable by each of [audiences].
Uint8List seal({
  required List<int> payload,
  required ObjectSlot object,
  required List<Audience> audiences,
  required Keyring keyring,
}) => RustLib.instance.api.crateApiSeal(
  payload: payload,
  object: object,
  audiences: audiences,
  keyring: keyring,
);

OpenedEnvelope open({required List<int> envelope, required Keyring keyring}) =>
    RustLib.instance.api.crateApiOpen(envelope: envelope, keyring: keyring);

/// Replaces who can read an object without re-encrypting it.
Uint8List rewrap({
  required List<int> envelope,
  required List<Audience> audiences,
  required Keyring keyring,
}) => RustLib.instance.api.crateApiRewrap(
  envelope: envelope,
  audiences: audiences,
  keyring: keyring,
);

/// Routing metadata, readable without keys.
EnvelopeHeader inspect({required List<int> envelope}) =>
    RustLib.instance.api.crateApiInspect(envelope: envelope);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Keyring>>
abstract class Keyring implements RustOpaqueInterface {
  bool contains({required String group, required int epoch});

  /// The raw key, for writing to platform secure storage.
  Uint8List exportKey({required String group, required int epoch});

  /// Creates a fresh random key for [group] at [epoch], replacing any held.
  void generate({required String group, required int epoch});

  /// Restores a key read back from platform secure storage.
  void importKey({
    required String group,
    required int epoch,
    required List<int> key,
  });

  factory Keyring() => RustLib.instance.api.crateApiKeyringNew();
}

/// An audience group at one epoch.
class Audience {
  final String group;
  final int epoch;

  const Audience({required this.group, required this.epoch});

  @override
  int get hashCode => group.hashCode ^ epoch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Audience &&
          runtimeType == other.runtimeType &&
          group == other.group &&
          epoch == other.epoch;
}

class EnvelopeError implements FrbException {
  final EnvelopeErrorKind kind;
  final String message;

  const EnvelopeError({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnvelopeError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

/// Why an envelope operation failed. A plain enum keeps the Dart side free of
/// code generation; the detail is in [EnvelopeError::message].
enum EnvelopeErrorKind {
  malformed,
  unsupportedVersion,
  unsupportedAlgorithm,

  /// This device holds no key for any audience of the object.
  noAccess,

  /// Altered, moved to another object, or opened with a wrong key.
  tampered,

  /// The keyring lacks a key the caller asked it to use.
  missingKey,
}

class EnvelopeHeader {
  final ObjectSlot object;
  final List<Audience> audiences;

  const EnvelopeHeader({required this.object, required this.audiences});

  @override
  int get hashCode => object.hashCode ^ audiences.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnvelopeHeader &&
          runtimeType == other.runtimeType &&
          object == other.object &&
          audiences == other.audiences;
}

/// Where an object lives: bound into its envelope so it can't be moved.
class ObjectSlot {
  final String objectType;
  final String id;
  final String familyId;

  const ObjectSlot({
    required this.objectType,
    required this.id,
    required this.familyId,
  });

  @override
  int get hashCode => objectType.hashCode ^ id.hashCode ^ familyId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ObjectSlot &&
          runtimeType == other.runtimeType &&
          objectType == other.objectType &&
          id == other.id &&
          familyId == other.familyId;
}

class OpenedEnvelope {
  final Uint8List payload;
  final EnvelopeHeader header;

  const OpenedEnvelope({required this.payload, required this.header});

  @override
  int get hashCode => payload.hashCode ^ header.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenedEnvelope &&
          runtimeType == other.runtimeType &&
          payload == other.payload &&
          header == other.header;
}
