// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `audience_keys`, `epoch_u32`, `key32`, `key`, `malformed`, `mls_peers`, `new`, `trusted_devices`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `try_from`, `try_from`

/// Who a grant claims to be from and for, without verifying it.
GrantInfo inspectGrant({required List<int> grant}) =>
    RustLib.instance.api.crateApiInspectGrant(grant: grant);

/// Vouches for [device] to the rest of the family, signed by [endorser].
Uint8List endorse({
  required Device endorser,
  required String endorserId,
  required String familyId,
  required DeviceRecord device,
}) => RustLib.instance.api.crateApiEndorse(
  endorser: endorser,
  endorserId: endorserId,
  familyId: familyId,
  device: device,
);

/// The device an endorsement from a trusted device vouches for.
DeviceRecord verifyEndorsement({
  required List<int> endorsement,
  required String familyId,
  required List<TrustedDevice> trusted,
}) => RustLib.instance.api.crateApiVerifyEndorsement(
  endorsement: endorsement,
  familyId: familyId,
  trusted: trusted,
);

/// Encrypts [payload] into [object]'s slot, readable by each of [audiences].
Uint8List seal({
  required List<int> payload,
  required ObjectSlot object,
  required List<Audience> audiences,
  required Keyring keyring,
}) => RustLib.instance.api.crateApiSeal(
  payload: payload,
  object: object,
  audiences: audiences,
  keyring: keyring,
);

OpenedEnvelope open({required List<int> envelope, required Keyring keyring}) =>
    RustLib.instance.api.crateApiOpen(envelope: envelope, keyring: keyring);

/// Replaces who can read an object without re-encrypting it.
Uint8List rewrap({
  required List<int> envelope,
  required List<Audience> audiences,
  required Keyring keyring,
}) => RustLib.instance.api.crateApiRewrap(
  envelope: envelope,
  audiences: audiences,
  keyring: keyring,
);

/// Routing metadata, readable without keys.
EnvelopeHeader inspect({required List<int> envelope}) =>
    RustLib.instance.api.crateApiInspect(envelope: envelope);

/// Twelve fresh words for a new recovery kit.
String recoveryWords() => RustLib.instance.api.crateApiRecoveryWords();

/// Opens twelve words: about a second of Argon2id, so it runs off the UI
/// thread. Refuses words not in the list and a checksum that doesn't hold.
Future<Recovery> openRecovery({required String words}) =>
    RustLib.instance.api.crateApiOpenRecovery(words: words);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Device>>
abstract class Device implements RustOpaqueInterface {
  /// The private keys, for storage encrypted under a hardware-backed key.
  /// Never send this anywhere.
  Uint8List exportSecret();

  /// A new identity, generated on first run.
  static Device generate() => RustLib.instance.api.crateApiDeviceGenerate();

  /// X25519 public key (32 bytes), published as the directory's KEM key.
  Uint8List get kemPublicKey;

  /// This device's public record, registered as [device_id].
  DeviceRecord record({required String deviceId});

  /// Restores an identity from [Device::export_secret]'s output.
  static Device restore({required List<int> secret}) =>
      RustLib.instance.api.crateApiDeviceRestore(secret: secret);

  /// Signs an API request as this device (crypto doc §2.2): the 64-byte
  /// value of the `X-Fam-Signature` header, before base64.
  Uint8List signRequest({
    required String deviceId,
    required String method,
    required String pathAndQuery,
    required BigInt timestampMs,
    required List<int> body,
  });

  /// Ed25519 public key (32 bytes), published as the directory's signing key.
  Uint8List get signingPublicKey;
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Keyring>>
abstract class Keyring implements RustOpaqueInterface {
  /// Verifies a grant addressed to [me] as [my_device] and adds its key.
  /// The group and epoch come from inside the signed grant, never from
  /// anything the server stores alongside it.
  Audience acceptGrant({
    required List<int> grant,
    required String familyId,
    required Device me,
    required String myDevice,
    required List<TrustedDevice> trusted,
  });

  bool contains({required String group, required int epoch});

  /// Creates a fresh random key for [group] at [epoch], replacing any held.
  /// Persist it by granting it to this device itself (see [Keyring::grant]).
  void generate({required String group, required int epoch});

  /// Seals the held key for [group] at [epoch] to another device (or to this
  /// one, for storage), signed by [granter] as [from_device].
  Uint8List grant({
    required String group,
    required int epoch,
    required String familyId,
    required Device granter,
    required String fromDevice,
    required String toDevice,
    required List<int> toKemKey,
  });

  /// The newest epoch held for [group], or null if none: new content is
  /// sealed to it, so a rotation takes effect on the next write.
  int? latestEpoch({required String group});

  factory Keyring() => RustLib.instance.api.crateApiKeyringNew();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Mls>>
abstract class Mls implements RustOpaqueInterface {
  MlsCommit addMembers({
    required Device device,
    required List<int> groupId,
    required List<Uint8List> keyPackages,
    required List<TrustedDevice> trusted,
  });

  void createGroup({
    required Device device,
    required String deviceId,
    required List<int> groupId,
  });

  void discardPending({required List<int> groupId});

  Uint8List encrypt({
    required Device device,
    required List<int> groupId,
    required List<int> content,
  });

  BigInt epoch({required List<int> groupId});

  /// Everything, for storage encrypted at rest.
  Uint8List exportState();

  void forgetGroup({required List<int> groupId});

  bool hasGroup({required List<int> groupId});

  /// Joins from a welcome; returns the group id.
  Uint8List join({
    required List<int> welcome,
    required List<TrustedDevice> trusted,
  });

  List<Uint8List> keyPackages({
    required Device device,
    required String deviceId,
    required int count,
  });

  List<String> members({required List<int> groupId});

  BigInt mergePending({required List<int> groupId});

  factory Mls() => RustLib.instance.api.crateApiMlsNew();

  MlsIncoming process({
    required List<int> groupId,
    required List<int> message,
    required List<TrustedDevice> trusted,
  });

  MlsCommit removeMembers({
    required Device device,
    required List<int> groupId,
    required List<String> deviceIds,
  });

  static Mls restore({required List<int> state}) =>
      RustLib.instance.api.crateApiMlsRestore(state: state);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PairingSession>>
abstract class PairingSession implements RustOpaqueInterface {
  /// Verifies the admission and returns where this device now belongs.
  Admitted accept({required List<int> admission});

  /// The text to render as a QR code. It holds a secret: show it on screen,
  /// never send or log it.
  String get code;

  /// Where the admission will arrive. Safe to send to the server.
  String get mailbox;

  static PairingSession start({required Device device}) =>
      RustLib.instance.api.crateApiPairingSessionStart(device: device);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Recovery>>
abstract class Recovery implements RustOpaqueInterface {
  /// The recovery device: registered on the kit maker's member and able to
  /// sign requests and accept grants like any device.
  Device device();

  /// Where the server keeps the kit.
  String get lookupId;

  Uint8List openNote({required List<int> sealed});

  Uint8List sealNote({required List<int> note});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ScannedCode>>
abstract class ScannedCode implements RustOpaqueInterface {
  /// The admission for the new device: [family_id], as [member_id], registered
  /// as [device_id], trusting [family_devices] with [from_device] (this
  /// device) among them.
  Uint8List admit({
    required String familyId,
    required String memberId,
    required String deviceId,
    required String fromDevice,
    required List<DeviceRecord> familyDevices,
  });

  /// The new device's X25519 key, as shown on its screen.
  Uint8List get kemKey;

  /// Where the new device is waiting for its admission.
  String get mailbox;

  static ScannedCode parse({required String code}) =>
      RustLib.instance.api.crateApiScannedCodeParse(code: code);

  /// The new device's record under the id it was registered with.
  DeviceRecord record({required String deviceId});

  /// The new device's Ed25519 key, as shown on its screen. Register the
  /// device with these keys, not any the server offers.
  Uint8List get signingKey;
}

/// What a new device learns from its admission.
class Admitted {
  final String familyId;
  final String memberId;
  final String deviceId;
  final List<DeviceRecord> trusted;

  const Admitted({
    required this.familyId,
    required this.memberId,
    required this.deviceId,
    required this.trusted,
  });

  @override
  int get hashCode =>
      familyId.hashCode ^
      memberId.hashCode ^
      deviceId.hashCode ^
      trusted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Admitted &&
          runtimeType == other.runtimeType &&
          familyId == other.familyId &&
          memberId == other.memberId &&
          deviceId == other.deviceId &&
          trusted == other.trusted;
}

/// An audience group at one epoch.
class Audience {
  final String group;
  final int epoch;

  const Audience({required this.group, required this.epoch});

  @override
  int get hashCode => group.hashCode ^ epoch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Audience &&
          runtimeType == other.runtimeType &&
          group == other.group &&
          epoch == other.epoch;
}

/// Why a crypto operation failed. A plain enum keeps the Dart side free of
/// code generation; the detail is in [CryptoException::message].
enum CryptoErrorKind {
  malformed,
  unsupportedVersion,
  unsupportedAlgorithm,

  /// This device holds no key for any audience of the object.
  noAccess,

  /// Altered, moved, or opened with a wrong key or signature.
  tampered,

  /// The keyring lacks a key the caller asked it to use.
  missingKey,

  /// A grant signed by a device this device doesn't trust.
  untrustedSender,

  /// A grant addressed to another device or family.
  wrongRecipient,
}

class CryptoException implements FrbException {
  final CryptoErrorKind kind;
  final String message;

  const CryptoException({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CryptoException &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

/// A device as the family knows it: its id and both 32-byte public keys.
class DeviceRecord {
  final String deviceId;
  final Uint8List signingKey;
  final Uint8List kemKey;

  const DeviceRecord({
    required this.deviceId,
    required this.signingKey,
    required this.kemKey,
  });

  @override
  int get hashCode => deviceId.hashCode ^ signingKey.hashCode ^ kemKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceRecord &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          signingKey == other.signingKey &&
          kemKey == other.kemKey;
}

class EnvelopeHeader {
  final ObjectSlot object;
  final List<Audience> audiences;

  const EnvelopeHeader({required this.object, required this.audiences});

  @override
  int get hashCode => object.hashCode ^ audiences.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnvelopeHeader &&
          runtimeType == other.runtimeType &&
          object == other.object &&
          audiences == other.audiences;
}

/// Who a grant claims to be from and for. Unverified: routing only.
class GrantInfo {
  final String familyId;
  final String group;
  final int epoch;
  final String toDevice;
  final String fromDevice;

  const GrantInfo({
    required this.familyId,
    required this.group,
    required this.epoch,
    required this.toDevice,
    required this.fromDevice,
  });

  @override
  int get hashCode =>
      familyId.hashCode ^
      group.hashCode ^
      epoch.hashCode ^
      toDevice.hashCode ^
      fromDevice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GrantInfo &&
          runtimeType == other.runtimeType &&
          familyId == other.familyId &&
          group == other.group &&
          epoch == other.epoch &&
          toDevice == other.toDevice &&
          fromDevice == other.fromDevice;
}

/// A membership change to send to the delivery service: merge it once
/// accepted, discard it if another got there first.
class MlsCommit {
  final Uint8List commit;

  /// Lets the added devices join; absent when only removing.
  final Uint8List? welcome;

  const MlsCommit({required this.commit, this.welcome});

  @override
  int get hashCode => commit.hashCode ^ welcome.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MlsCommit &&
          runtimeType == other.runtimeType &&
          commit == other.commit &&
          welcome == other.welcome;
}

/// What one message from the delivery service turned out to be.
class MlsIncoming {
  final MlsIncomingKind kind;
  final String? sender;
  final Uint8List? content;
  final BigInt? epoch;

  const MlsIncoming({
    required this.kind,
    this.sender,
    this.content,
    this.epoch,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ sender.hashCode ^ content.hashCode ^ epoch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MlsIncoming &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          sender == other.sender &&
          content == other.content &&
          epoch == other.epoch;
}

enum MlsIncomingKind {
  /// A chat message: [MlsIncoming::sender] and [MlsIncoming::content].
  application,

  /// A membership change, merged: [MlsIncoming::epoch].
  commit,

  /// This device's own message, echoed back.
  own,
}

/// Where an object lives: bound into its envelope so it can't be moved.
class ObjectSlot {
  final String objectType;
  final String id;
  final String familyId;

  const ObjectSlot({
    required this.objectType,
    required this.id,
    required this.familyId,
  });

  @override
  int get hashCode => objectType.hashCode ^ id.hashCode ^ familyId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ObjectSlot &&
          runtimeType == other.runtimeType &&
          objectType == other.objectType &&
          id == other.id &&
          familyId == other.familyId;
}

class OpenedEnvelope {
  final Uint8List payload;
  final EnvelopeHeader header;

  const OpenedEnvelope({required this.payload, required this.header});

  @override
  int get hashCode => payload.hashCode ^ header.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenedEnvelope &&
          runtimeType == other.runtimeType &&
          payload == other.payload &&
          header == other.header;
}

/// A device this device already trusts: pinned at provisioning time after the
/// out-of-band comparison, never taken on the server's word alone.
class TrustedDevice {
  final String deviceId;
  final Uint8List signingKey;

  const TrustedDevice({required this.deviceId, required this.signingKey});

  @override
  int get hashCode => deviceId.hashCode ^ signingKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrustedDevice &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          signingKey == other.signingKey;
}
