// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1065665878;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'family_crypto',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Uint8List crateApiDeviceExportSecret({required Device that});

  Device crateApiDeviceGenerate();

  Uint8List crateApiDeviceKemPublicKey({required Device that});

  DeviceRecord crateApiDeviceRecord({
    required Device that,
    required String deviceId,
  });

  Device crateApiDeviceRestore({required List<int> secret});

  Uint8List crateApiDeviceSignRequest({
    required Device that,
    required String deviceId,
    required String method,
    required String pathAndQuery,
    required BigInt timestampMs,
    required List<int> body,
  });

  Uint8List crateApiDeviceSigningPublicKey({required Device that});

  Audience crateApiKeyringAcceptGrant({
    required Keyring that,
    required List<int> grant,
    required String familyId,
    required Device me,
    required String myDevice,
    required List<TrustedDevice> trusted,
  });

  bool crateApiKeyringContains({
    required Keyring that,
    required String group,
    required int epoch,
  });

  void crateApiKeyringGenerate({
    required Keyring that,
    required String group,
    required int epoch,
  });

  Uint8List crateApiKeyringGrant({
    required Keyring that,
    required String group,
    required int epoch,
    required String familyId,
    required Device granter,
    required String fromDevice,
    required String toDevice,
    required List<int> toKemKey,
  });

  Keyring crateApiKeyringNew();

  Admitted crateApiPairingSessionAccept({
    required PairingSession that,
    required List<int> admission,
  });

  String crateApiPairingSessionCode({required PairingSession that});

  String crateApiPairingSessionMailbox({required PairingSession that});

  PairingSession crateApiPairingSessionStart({required Device device});

  Uint8List crateApiScannedCodeAdmit({
    required ScannedCode that,
    required String familyId,
    required String memberId,
    required String deviceId,
    required String fromDevice,
    required List<DeviceRecord> familyDevices,
  });

  Uint8List crateApiScannedCodeKemKey({required ScannedCode that});

  String crateApiScannedCodeMailbox({required ScannedCode that});

  ScannedCode crateApiScannedCodeParse({required String code});

  DeviceRecord crateApiScannedCodeRecord({
    required ScannedCode that,
    required String deviceId,
  });

  Uint8List crateApiScannedCodeSigningKey({required ScannedCode that});

  Uint8List crateApiEndorse({
    required Device endorser,
    required String endorserId,
    required String familyId,
    required DeviceRecord device,
  });

  Future<void> crateApiInitApp();

  EnvelopeHeader crateApiInspect({required List<int> envelope});

  GrantInfo crateApiInspectGrant({required List<int> grant});

  OpenedEnvelope crateApiOpen({
    required List<int> envelope,
    required Keyring keyring,
  });

  Uint8List crateApiRewrap({
    required List<int> envelope,
    required List<Audience> audiences,
    required Keyring keyring,
  });

  Uint8List crateApiSeal({
    required List<int> payload,
    required ObjectSlot object,
    required List<Audience> audiences,
    required Keyring keyring,
  });

  DeviceRecord crateApiVerifyEndorsement({
    required List<int> endorsement,
    required String familyId,
    required List<TrustedDevice> trusted,
  });

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Device;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Device;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_DevicePtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Keyring;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Keyring;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_KeyringPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_PairingSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_PairingSession;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PairingSessionPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ScannedCode;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ScannedCode;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ScannedCodePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Uint8List crateApiDeviceExportSecret({required Device that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDeviceExportSecretConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceExportSecretConstMeta => const TaskConstMeta(
    debugName: "Device_export_secret",
    argNames: ["that"],
  );

  @override
  Device crateApiDeviceGenerate() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDeviceGenerateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceGenerateConstMeta =>
      const TaskConstMeta(debugName: "Device_generate", argNames: []);

  @override
  Uint8List crateApiDeviceKemPublicKey({required Device that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDeviceKemPublicKeyConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceKemPublicKeyConstMeta => const TaskConstMeta(
    debugName: "Device_kem_public_key",
    argNames: ["that"],
  );

  @override
  DeviceRecord crateApiDeviceRecord({
    required Device that,
    required String deviceId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
            that,
            serializer,
          );
          sse_encode_String(deviceId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_record,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDeviceRecordConstMeta,
        argValues: [that, deviceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceRecordConstMeta => const TaskConstMeta(
    debugName: "Device_record",
    argNames: ["that", "deviceId"],
  );

  @override
  Device crateApiDeviceRestore({required List<int> secret}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(secret, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice,
          decodeErrorData: sse_decode_crypto_exception,
        ),
        constMeta: kCrateApiDeviceRestoreConstMeta,
        argValues: [secret],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceRestoreConstMeta =>
      const TaskConstMeta(debugName: "Device_restore", argNames: ["secret"]);

  @override
  Uint8List crateApiDeviceSignRequest({
    required Device that,
    required String deviceId,
    required String method,
    required String pathAndQuery,
    required BigInt timestampMs,
    required List<int> body,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
            that,
            serializer,
          );
          sse_encode_String(deviceId, serializer);
          sse_encode_String(method, serializer);
          sse_encode_String(pathAndQuery, serializer);
          sse_encode_u_64(timestampMs, serializer);
          sse_encode_list_prim_u_8_loose(body, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_crypto_exception,
        ),
        constMeta: kCrateApiDeviceSignRequestConstMeta,
        argValues: [that, deviceId, method, pathAndQuery, timestampMs, body],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceSignRequestConstMeta => const TaskConstMeta(
    debugName: "Device_sign_request",
    argNames: [
      "that",
      "deviceId",
      "method",
      "pathAndQuery",
      "timestampMs",
      "body",
    ],
  );

  @override
  Uint8List crateApiDeviceSigningPublicKey({required Device that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDeviceSigningPublicKeyConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceSigningPublicKeyConstMeta =>
      const TaskConstMeta(
        debugName: "Device_signing_public_key",
        argNames: ["that"],
      );

  @override
  Audience crateApiKeyringAcceptGrant({
    required Keyring that,
    required List<int> grant,
    required String familyId,
    required Device me,
    required String myDevice,
    required List<TrustedDevice> trusted,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(grant, serializer);
          sse_encode_String(familyId, serializer);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
            me,
            serializer,
          );
          sse_encode_String(myDevice, serializer);
          sse_encode_list_trusted_device(trusted, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_audience,
          decodeErrorData: sse_decode_crypto_exception,
        ),
        constMeta: kCrateApiKeyringAcceptGrantConstMeta,
        argValues: [that, grant, familyId, me, myDevice, trusted],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeyringAcceptGrantConstMeta => const TaskConstMeta(
    debugName: "Keyring_accept_grant",
    argNames: ["that", "grant", "familyId", "me", "myDevice", "trusted"],
  );

  @override
  bool crateApiKeyringContains({
    required Keyring that,
    required String group,
    required int epoch,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
            that,
            serializer,
          );
          sse_encode_String(group, serializer);
          sse_encode_u_32(epoch, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKeyringContainsConstMeta,
        argValues: [that, group, epoch],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeyringContainsConstMeta => const TaskConstMeta(
    debugName: "Keyring_contains",
    argNames: ["that", "group", "epoch"],
  );

  @override
  void crateApiKeyringGenerate({
    required Keyring that,
    required String group,
    required int epoch,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
            that,
            serializer,
          );
          sse_encode_String(group, serializer);
          sse_encode_u_32(epoch, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKeyringGenerateConstMeta,
        argValues: [that, group, epoch],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeyringGenerateConstMeta => const TaskConstMeta(
    debugName: "Keyring_generate",
    argNames: ["that", "group", "epoch"],
  );

  @override
  Uint8List crateApiKeyringGrant({
    required Keyring that,
    required String group,
    required int epoch,
    required String familyId,
    required Device granter,
    required String fromDevice,
    required String toDevice,
    required List<int> toKemKey,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
            that,
            serializer,
          );
          sse_encode_String(group, serializer);
          sse_encode_u_32(epoch, serializer);
          sse_encode_String(familyId, serializer);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
            granter,
            serializer,
          );
          sse_encode_String(fromDevice, serializer);
          sse_encode_String(toDevice, serializer);
          sse_encode_list_prim_u_8_loose(toKemKey, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_crypto_exception,
        ),
        constMeta: kCrateApiKeyringGrantConstMeta,
        argValues: [
          that,
          group,
          epoch,
          familyId,
          granter,
          fromDevice,
          toDevice,
          toKemKey,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeyringGrantConstMeta => const TaskConstMeta(
    debugName: "Keyring_grant",
    argNames: [
      "that",
      "group",
      "epoch",
      "familyId",
      "granter",
      "fromDevice",
      "toDevice",
      "toKemKey",
    ],
  );

  @override
  Keyring crateApiKeyringNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKeyringNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeyringNewConstMeta =>
      const TaskConstMeta(debugName: "Keyring_new", argNames: []);

  @override
  Admitted crateApiPairingSessionAccept({
    required PairingSession that,
    required List<int> admission,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSession(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(admission, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_admitted,
          decodeErrorData: sse_decode_crypto_exception,
        ),
        constMeta: kCrateApiPairingSessionAcceptConstMeta,
        argValues: [that, admission],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPairingSessionAcceptConstMeta =>
      const TaskConstMeta(
        debugName: "PairingSession_accept",
        argNames: ["that", "admission"],
      );

  @override
  String crateApiPairingSessionCode({required PairingSession that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSession(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPairingSessionCodeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPairingSessionCodeConstMeta =>
      const TaskConstMeta(debugName: "PairingSession_code", argNames: ["that"]);

  @override
  String crateApiPairingSessionMailbox({required PairingSession that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSession(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPairingSessionMailboxConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPairingSessionMailboxConstMeta =>
      const TaskConstMeta(
        debugName: "PairingSession_mailbox",
        argNames: ["that"],
      );

  @override
  PairingSession crateApiPairingSessionStart({required Device device}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
            device,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSession,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPairingSessionStartConstMeta,
        argValues: [device],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPairingSessionStartConstMeta =>
      const TaskConstMeta(
        debugName: "PairingSession_start",
        argNames: ["device"],
      );

  @override
  Uint8List crateApiScannedCodeAdmit({
    required ScannedCode that,
    required String familyId,
    required String memberId,
    required String deviceId,
    required String fromDevice,
    required List<DeviceRecord> familyDevices,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScannedCode(
            that,
            serializer,
          );
          sse_encode_String(familyId, serializer);
          sse_encode_String(memberId, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(fromDevice, serializer);
          sse_encode_list_device_record(familyDevices, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_crypto_exception,
        ),
        constMeta: kCrateApiScannedCodeAdmitConstMeta,
        argValues: [
          that,
          familyId,
          memberId,
          deviceId,
          fromDevice,
          familyDevices,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScannedCodeAdmitConstMeta => const TaskConstMeta(
    debugName: "ScannedCode_admit",
    argNames: [
      "that",
      "familyId",
      "memberId",
      "deviceId",
      "fromDevice",
      "familyDevices",
    ],
  );

  @override
  Uint8List crateApiScannedCodeKemKey({required ScannedCode that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScannedCode(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScannedCodeKemKeyConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScannedCodeKemKeyConstMeta =>
      const TaskConstMeta(debugName: "ScannedCode_kem_key", argNames: ["that"]);

  @override
  String crateApiScannedCodeMailbox({required ScannedCode that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScannedCode(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScannedCodeMailboxConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScannedCodeMailboxConstMeta =>
      const TaskConstMeta(debugName: "ScannedCode_mailbox", argNames: ["that"]);

  @override
  ScannedCode crateApiScannedCodeParse({required String code}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(code, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScannedCode,
          decodeErrorData: sse_decode_crypto_exception,
        ),
        constMeta: kCrateApiScannedCodeParseConstMeta,
        argValues: [code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScannedCodeParseConstMeta =>
      const TaskConstMeta(debugName: "ScannedCode_parse", argNames: ["code"]);

  @override
  DeviceRecord crateApiScannedCodeRecord({
    required ScannedCode that,
    required String deviceId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScannedCode(
            that,
            serializer,
          );
          sse_encode_String(deviceId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_record,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScannedCodeRecordConstMeta,
        argValues: [that, deviceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScannedCodeRecordConstMeta => const TaskConstMeta(
    debugName: "ScannedCode_record",
    argNames: ["that", "deviceId"],
  );

  @override
  Uint8List crateApiScannedCodeSigningKey({required ScannedCode that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScannedCode(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScannedCodeSigningKeyConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScannedCodeSigningKeyConstMeta =>
      const TaskConstMeta(
        debugName: "ScannedCode_signing_key",
        argNames: ["that"],
      );

  @override
  Uint8List crateApiEndorse({
    required Device endorser,
    required String endorserId,
    required String familyId,
    required DeviceRecord device,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
            endorser,
            serializer,
          );
          sse_encode_String(endorserId, serializer);
          sse_encode_String(familyId, serializer);
          sse_encode_box_autoadd_device_record(device, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_crypto_exception,
        ),
        constMeta: kCrateApiEndorseConstMeta,
        argValues: [endorser, endorserId, familyId, device],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEndorseConstMeta => const TaskConstMeta(
    debugName: "endorse",
    argNames: ["endorser", "endorserId", "familyId", "device"],
  );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  EnvelopeHeader crateApiInspect({required List<int> envelope}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(envelope, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_envelope_header,
          decodeErrorData: sse_decode_crypto_exception,
        ),
        constMeta: kCrateApiInspectConstMeta,
        argValues: [envelope],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInspectConstMeta =>
      const TaskConstMeta(debugName: "inspect", argNames: ["envelope"]);

  @override
  GrantInfo crateApiInspectGrant({required List<int> grant}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(grant, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_grant_info,
          decodeErrorData: sse_decode_crypto_exception,
        ),
        constMeta: kCrateApiInspectGrantConstMeta,
        argValues: [grant],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInspectGrantConstMeta =>
      const TaskConstMeta(debugName: "inspect_grant", argNames: ["grant"]);

  @override
  OpenedEnvelope crateApiOpen({
    required List<int> envelope,
    required Keyring keyring,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(envelope, serializer);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
            keyring,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opened_envelope,
          decodeErrorData: sse_decode_crypto_exception,
        ),
        constMeta: kCrateApiOpenConstMeta,
        argValues: [envelope, keyring],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpenConstMeta =>
      const TaskConstMeta(debugName: "open", argNames: ["envelope", "keyring"]);

  @override
  Uint8List crateApiRewrap({
    required List<int> envelope,
    required List<Audience> audiences,
    required Keyring keyring,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(envelope, serializer);
          sse_encode_list_audience(audiences, serializer);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
            keyring,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_crypto_exception,
        ),
        constMeta: kCrateApiRewrapConstMeta,
        argValues: [envelope, audiences, keyring],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRewrapConstMeta => const TaskConstMeta(
    debugName: "rewrap",
    argNames: ["envelope", "audiences", "keyring"],
  );

  @override
  Uint8List crateApiSeal({
    required List<int> payload,
    required ObjectSlot object,
    required List<Audience> audiences,
    required Keyring keyring,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(payload, serializer);
          sse_encode_box_autoadd_object_slot(object, serializer);
          sse_encode_list_audience(audiences, serializer);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
            keyring,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_crypto_exception,
        ),
        constMeta: kCrateApiSealConstMeta,
        argValues: [payload, object, audiences, keyring],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSealConstMeta => const TaskConstMeta(
    debugName: "seal",
    argNames: ["payload", "object", "audiences", "keyring"],
  );

  @override
  DeviceRecord crateApiVerifyEndorsement({
    required List<int> endorsement,
    required String familyId,
    required List<TrustedDevice> trusted,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(endorsement, serializer);
          sse_encode_String(familyId, serializer);
          sse_encode_list_trusted_device(trusted, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_record,
          decodeErrorData: sse_decode_crypto_exception,
        ),
        constMeta: kCrateApiVerifyEndorsementConstMeta,
        argValues: [endorsement, familyId, trusted],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVerifyEndorsementConstMeta => const TaskConstMeta(
    debugName: "verify_endorsement",
    argNames: ["endorsement", "familyId", "trusted"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Device => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Device => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Keyring => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Keyring => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_PairingSession => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_PairingSession => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSession;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ScannedCode => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScannedCode;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ScannedCode => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScannedCode;

  @protected
  Device
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DeviceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Keyring
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KeyringImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PairingSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PairingSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ScannedCode
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScannedCode(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ScannedCodeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Keyring
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KeyringImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Device
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DeviceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Keyring
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KeyringImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PairingSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PairingSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ScannedCode
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScannedCode(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ScannedCodeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Device
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DeviceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Keyring
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KeyringImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PairingSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PairingSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ScannedCode
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScannedCode(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ScannedCodeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Admitted dco_decode_admitted(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Admitted(
      familyId: dco_decode_String(arr[0]),
      memberId: dco_decode_String(arr[1]),
      deviceId: dco_decode_String(arr[2]),
      trusted: dco_decode_list_device_record(arr[3]),
    );
  }

  @protected
  Audience dco_decode_audience(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Audience(
      group: dco_decode_String(arr[0]),
      epoch: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DeviceRecord dco_decode_box_autoadd_device_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_device_record(raw);
  }

  @protected
  ObjectSlot dco_decode_box_autoadd_object_slot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_object_slot(raw);
  }

  @protected
  CryptoErrorKind dco_decode_crypto_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CryptoErrorKind.values[raw as int];
  }

  @protected
  CryptoException dco_decode_crypto_exception(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CryptoException(
      kind: dco_decode_crypto_error_kind(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  DeviceRecord dco_decode_device_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DeviceRecord(
      deviceId: dco_decode_String(arr[0]),
      signingKey: dco_decode_list_prim_u_8_strict(arr[1]),
      kemKey: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  EnvelopeHeader dco_decode_envelope_header(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return EnvelopeHeader(
      object: dco_decode_object_slot(arr[0]),
      audiences: dco_decode_list_audience(arr[1]),
    );
  }

  @protected
  GrantInfo dco_decode_grant_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return GrantInfo(
      familyId: dco_decode_String(arr[0]),
      group: dco_decode_String(arr[1]),
      epoch: dco_decode_u_32(arr[2]),
      toDevice: dco_decode_String(arr[3]),
      fromDevice: dco_decode_String(arr[4]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<Audience> dco_decode_list_audience(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_audience).toList();
  }

  @protected
  List<DeviceRecord> dco_decode_list_device_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_device_record).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TrustedDevice> dco_decode_list_trusted_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_trusted_device).toList();
  }

  @protected
  ObjectSlot dco_decode_object_slot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ObjectSlot(
      objectType: dco_decode_String(arr[0]),
      id: dco_decode_String(arr[1]),
      familyId: dco_decode_String(arr[2]),
    );
  }

  @protected
  OpenedEnvelope dco_decode_opened_envelope(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return OpenedEnvelope(
      payload: dco_decode_list_prim_u_8_strict(arr[0]),
      header: dco_decode_envelope_header(arr[1]),
    );
  }

  @protected
  TrustedDevice dco_decode_trusted_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TrustedDevice(
      deviceId: dco_decode_String(arr[0]),
      signingKey: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Device
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DeviceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Keyring
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KeyringImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  PairingSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PairingSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ScannedCode
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScannedCode(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ScannedCodeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Keyring
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KeyringImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Device
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DeviceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Keyring
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KeyringImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  PairingSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PairingSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ScannedCode
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScannedCode(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ScannedCodeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Device
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DeviceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Keyring
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KeyringImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  PairingSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PairingSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ScannedCode
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScannedCode(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ScannedCodeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Admitted sse_decode_admitted(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_familyId = sse_decode_String(deserializer);
    var var_memberId = sse_decode_String(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    var var_trusted = sse_decode_list_device_record(deserializer);
    return Admitted(
      familyId: var_familyId,
      memberId: var_memberId,
      deviceId: var_deviceId,
      trusted: var_trusted,
    );
  }

  @protected
  Audience sse_decode_audience(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_group = sse_decode_String(deserializer);
    var var_epoch = sse_decode_u_32(deserializer);
    return Audience(group: var_group, epoch: var_epoch);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DeviceRecord sse_decode_box_autoadd_device_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_device_record(deserializer));
  }

  @protected
  ObjectSlot sse_decode_box_autoadd_object_slot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_object_slot(deserializer));
  }

  @protected
  CryptoErrorKind sse_decode_crypto_error_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CryptoErrorKind.values[inner];
  }

  @protected
  CryptoException sse_decode_crypto_exception(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_crypto_error_kind(deserializer);
    var var_message = sse_decode_String(deserializer);
    return CryptoException(kind: var_kind, message: var_message);
  }

  @protected
  DeviceRecord sse_decode_device_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_signingKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_kemKey = sse_decode_list_prim_u_8_strict(deserializer);
    return DeviceRecord(
      deviceId: var_deviceId,
      signingKey: var_signingKey,
      kemKey: var_kemKey,
    );
  }

  @protected
  EnvelopeHeader sse_decode_envelope_header(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_object = sse_decode_object_slot(deserializer);
    var var_audiences = sse_decode_list_audience(deserializer);
    return EnvelopeHeader(object: var_object, audiences: var_audiences);
  }

  @protected
  GrantInfo sse_decode_grant_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_familyId = sse_decode_String(deserializer);
    var var_group = sse_decode_String(deserializer);
    var var_epoch = sse_decode_u_32(deserializer);
    var var_toDevice = sse_decode_String(deserializer);
    var var_fromDevice = sse_decode_String(deserializer);
    return GrantInfo(
      familyId: var_familyId,
      group: var_group,
      epoch: var_epoch,
      toDevice: var_toDevice,
      fromDevice: var_fromDevice,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<Audience> sse_decode_list_audience(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Audience>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_audience(deserializer));
    }
    return ans_;
  }

  @protected
  List<DeviceRecord> sse_decode_list_device_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DeviceRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_device_record(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TrustedDevice> sse_decode_list_trusted_device(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TrustedDevice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_trusted_device(deserializer));
    }
    return ans_;
  }

  @protected
  ObjectSlot sse_decode_object_slot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_objectType = sse_decode_String(deserializer);
    var var_id = sse_decode_String(deserializer);
    var var_familyId = sse_decode_String(deserializer);
    return ObjectSlot(
      objectType: var_objectType,
      id: var_id,
      familyId: var_familyId,
    );
  }

  @protected
  OpenedEnvelope sse_decode_opened_envelope(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_payload = sse_decode_list_prim_u_8_strict(deserializer);
    var var_header = sse_decode_envelope_header(deserializer);
    return OpenedEnvelope(payload: var_payload, header: var_header);
  }

  @protected
  TrustedDevice sse_decode_trusted_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_signingKey = sse_decode_list_prim_u_8_strict(deserializer);
    return TrustedDevice(deviceId: var_deviceId, signingKey: var_signingKey);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
    Device self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as DeviceImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    Keyring self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KeyringImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSession(
    PairingSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PairingSessionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScannedCode(
    ScannedCode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ScannedCodeImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    Keyring self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KeyringImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
    Device self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as DeviceImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    Keyring self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KeyringImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSession(
    PairingSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PairingSessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScannedCode(
    ScannedCode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ScannedCodeImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDevice(
    Device self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as DeviceImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    Keyring self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KeyringImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPairingSession(
    PairingSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PairingSessionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerScannedCode(
    ScannedCode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ScannedCodeImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_admitted(Admitted self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.familyId, serializer);
    sse_encode_String(self.memberId, serializer);
    sse_encode_String(self.deviceId, serializer);
    sse_encode_list_device_record(self.trusted, serializer);
  }

  @protected
  void sse_encode_audience(Audience self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.group, serializer);
    sse_encode_u_32(self.epoch, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_device_record(
    DeviceRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_device_record(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_object_slot(
    ObjectSlot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_object_slot(self, serializer);
  }

  @protected
  void sse_encode_crypto_error_kind(
    CryptoErrorKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_crypto_exception(
    CryptoException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_crypto_error_kind(self.kind, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_device_record(DeviceRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_list_prim_u_8_strict(self.signingKey, serializer);
    sse_encode_list_prim_u_8_strict(self.kemKey, serializer);
  }

  @protected
  void sse_encode_envelope_header(
    EnvelopeHeader self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_object_slot(self.object, serializer);
    sse_encode_list_audience(self.audiences, serializer);
  }

  @protected
  void sse_encode_grant_info(GrantInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.familyId, serializer);
    sse_encode_String(self.group, serializer);
    sse_encode_u_32(self.epoch, serializer);
    sse_encode_String(self.toDevice, serializer);
    sse_encode_String(self.fromDevice, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_audience(List<Audience> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_audience(item, serializer);
    }
  }

  @protected
  void sse_encode_list_device_record(
    List<DeviceRecord> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_device_record(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_trusted_device(
    List<TrustedDevice> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_trusted_device(item, serializer);
    }
  }

  @protected
  void sse_encode_object_slot(ObjectSlot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.objectType, serializer);
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.familyId, serializer);
  }

  @protected
  void sse_encode_opened_envelope(
    OpenedEnvelope self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.payload, serializer);
    sse_encode_envelope_header(self.header, serializer);
  }

  @protected
  void sse_encode_trusted_device(TrustedDevice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_list_prim_u_8_strict(self.signingKey, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class DeviceImpl extends RustOpaque implements Device {
  // Not to be used by end users
  DeviceImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  DeviceImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Device,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Device,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_DevicePtr,
  );

  /// The private keys, for storage encrypted under a hardware-backed key.
  /// Never send this anywhere.
  Uint8List exportSecret() =>
      RustLib.instance.api.crateApiDeviceExportSecret(that: this);

  /// X25519 public key (32 bytes), published as the directory's KEM key.
  Uint8List get kemPublicKey =>
      RustLib.instance.api.crateApiDeviceKemPublicKey(that: this);

  /// This device's public record, registered as [device_id].
  DeviceRecord record({required String deviceId}) =>
      RustLib.instance.api.crateApiDeviceRecord(that: this, deviceId: deviceId);

  /// Signs an API request as this device (crypto doc §2.2): the 64-byte
  /// value of the `X-Fam-Signature` header, before base64.
  Uint8List signRequest({
    required String deviceId,
    required String method,
    required String pathAndQuery,
    required BigInt timestampMs,
    required List<int> body,
  }) => RustLib.instance.api.crateApiDeviceSignRequest(
    that: this,
    deviceId: deviceId,
    method: method,
    pathAndQuery: pathAndQuery,
    timestampMs: timestampMs,
    body: body,
  );

  /// Ed25519 public key (32 bytes), published as the directory's signing key.
  Uint8List get signingPublicKey =>
      RustLib.instance.api.crateApiDeviceSigningPublicKey(that: this);
}

@sealed
class KeyringImpl extends RustOpaque implements Keyring {
  // Not to be used by end users
  KeyringImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  KeyringImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Keyring,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Keyring,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_KeyringPtr,
  );

  /// Verifies a grant addressed to [me] as [my_device] and adds its key.
  /// The group and epoch come from inside the signed grant, never from
  /// anything the server stores alongside it.
  Audience acceptGrant({
    required List<int> grant,
    required String familyId,
    required Device me,
    required String myDevice,
    required List<TrustedDevice> trusted,
  }) => RustLib.instance.api.crateApiKeyringAcceptGrant(
    that: this,
    grant: grant,
    familyId: familyId,
    me: me,
    myDevice: myDevice,
    trusted: trusted,
  );

  bool contains({required String group, required int epoch}) => RustLib
      .instance
      .api
      .crateApiKeyringContains(that: this, group: group, epoch: epoch);

  /// Creates a fresh random key for [group] at [epoch], replacing any held.
  /// Persist it by granting it to this device itself (see [Keyring::grant]).
  void generate({required String group, required int epoch}) => RustLib
      .instance
      .api
      .crateApiKeyringGenerate(that: this, group: group, epoch: epoch);

  /// Seals the held key for [group] at [epoch] to another device (or to this
  /// one, for storage), signed by [granter] as [from_device].
  Uint8List grant({
    required String group,
    required int epoch,
    required String familyId,
    required Device granter,
    required String fromDevice,
    required String toDevice,
    required List<int> toKemKey,
  }) => RustLib.instance.api.crateApiKeyringGrant(
    that: this,
    group: group,
    epoch: epoch,
    familyId: familyId,
    granter: granter,
    fromDevice: fromDevice,
    toDevice: toDevice,
    toKemKey: toKemKey,
  );
}

@sealed
class PairingSessionImpl extends RustOpaque implements PairingSession {
  // Not to be used by end users
  PairingSessionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  PairingSessionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_PairingSession,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_PairingSession,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_PairingSessionPtr,
  );

  /// Verifies the admission and returns where this device now belongs.
  Admitted accept({required List<int> admission}) => RustLib.instance.api
      .crateApiPairingSessionAccept(that: this, admission: admission);

  /// The text to render as a QR code. It holds a secret: show it on screen,
  /// never send or log it.
  String get code =>
      RustLib.instance.api.crateApiPairingSessionCode(that: this);

  /// Where the admission will arrive. Safe to send to the server.
  String get mailbox =>
      RustLib.instance.api.crateApiPairingSessionMailbox(that: this);
}

@sealed
class ScannedCodeImpl extends RustOpaque implements ScannedCode {
  // Not to be used by end users
  ScannedCodeImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ScannedCodeImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ScannedCode,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ScannedCode,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ScannedCodePtr,
  );

  /// The admission for the new device: [family_id], as [member_id], registered
  /// as [device_id], trusting [family_devices] with [from_device] (this
  /// device) among them.
  Uint8List admit({
    required String familyId,
    required String memberId,
    required String deviceId,
    required String fromDevice,
    required List<DeviceRecord> familyDevices,
  }) => RustLib.instance.api.crateApiScannedCodeAdmit(
    that: this,
    familyId: familyId,
    memberId: memberId,
    deviceId: deviceId,
    fromDevice: fromDevice,
    familyDevices: familyDevices,
  );

  /// The new device's X25519 key, as shown on its screen.
  Uint8List get kemKey =>
      RustLib.instance.api.crateApiScannedCodeKemKey(that: this);

  /// Where the new device is waiting for its admission.
  String get mailbox =>
      RustLib.instance.api.crateApiScannedCodeMailbox(that: this);

  /// The new device's record under the id it was registered with.
  DeviceRecord record({required String deviceId}) => RustLib.instance.api
      .crateApiScannedCodeRecord(that: this, deviceId: deviceId);

  /// The new device's Ed25519 key, as shown on its screen. Register the
  /// device with these keys, not any the server offers.
  Uint8List get signingKey =>
      RustLib.instance.api.crateApiScannedCodeSigningKey(that: this);
}
