// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -281143915;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'family_crypto',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  bool crateApiKeyringContains({
    required Keyring that,
    required String group,
    required int epoch,
  });

  Uint8List crateApiKeyringExportKey({
    required Keyring that,
    required String group,
    required int epoch,
  });

  void crateApiKeyringGenerate({
    required Keyring that,
    required String group,
    required int epoch,
  });

  void crateApiKeyringImportKey({
    required Keyring that,
    required String group,
    required int epoch,
    required List<int> key,
  });

  Keyring crateApiKeyringNew();

  Future<void> crateApiInitApp();

  EnvelopeHeader crateApiInspect({required List<int> envelope});

  OpenedEnvelope crateApiOpen({
    required List<int> envelope,
    required Keyring keyring,
  });

  Uint8List crateApiRewrap({
    required List<int> envelope,
    required List<Audience> audiences,
    required Keyring keyring,
  });

  Uint8List crateApiSeal({
    required List<int> payload,
    required ObjectSlot object,
    required List<Audience> audiences,
    required Keyring keyring,
  });

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Keyring;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Keyring;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_KeyringPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  bool crateApiKeyringContains({
    required Keyring that,
    required String group,
    required int epoch,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
            that,
            serializer,
          );
          sse_encode_String(group, serializer);
          sse_encode_u_32(epoch, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKeyringContainsConstMeta,
        argValues: [that, group, epoch],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeyringContainsConstMeta => const TaskConstMeta(
    debugName: "Keyring_contains",
    argNames: ["that", "group", "epoch"],
  );

  @override
  Uint8List crateApiKeyringExportKey({
    required Keyring that,
    required String group,
    required int epoch,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
            that,
            serializer,
          );
          sse_encode_String(group, serializer);
          sse_encode_u_32(epoch, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_envelope_error,
        ),
        constMeta: kCrateApiKeyringExportKeyConstMeta,
        argValues: [that, group, epoch],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeyringExportKeyConstMeta => const TaskConstMeta(
    debugName: "Keyring_export_key",
    argNames: ["that", "group", "epoch"],
  );

  @override
  void crateApiKeyringGenerate({
    required Keyring that,
    required String group,
    required int epoch,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
            that,
            serializer,
          );
          sse_encode_String(group, serializer);
          sse_encode_u_32(epoch, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKeyringGenerateConstMeta,
        argValues: [that, group, epoch],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeyringGenerateConstMeta => const TaskConstMeta(
    debugName: "Keyring_generate",
    argNames: ["that", "group", "epoch"],
  );

  @override
  void crateApiKeyringImportKey({
    required Keyring that,
    required String group,
    required int epoch,
    required List<int> key,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
            that,
            serializer,
          );
          sse_encode_String(group, serializer);
          sse_encode_u_32(epoch, serializer);
          sse_encode_list_prim_u_8_loose(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_envelope_error,
        ),
        constMeta: kCrateApiKeyringImportKeyConstMeta,
        argValues: [that, group, epoch, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeyringImportKeyConstMeta => const TaskConstMeta(
    debugName: "Keyring_import_key",
    argNames: ["that", "group", "epoch", "key"],
  );

  @override
  Keyring crateApiKeyringNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKeyringNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeyringNewConstMeta =>
      const TaskConstMeta(debugName: "Keyring_new", argNames: []);

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  EnvelopeHeader crateApiInspect({required List<int> envelope}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(envelope, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_envelope_header,
          decodeErrorData: sse_decode_envelope_error,
        ),
        constMeta: kCrateApiInspectConstMeta,
        argValues: [envelope],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInspectConstMeta =>
      const TaskConstMeta(debugName: "inspect", argNames: ["envelope"]);

  @override
  OpenedEnvelope crateApiOpen({
    required List<int> envelope,
    required Keyring keyring,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(envelope, serializer);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
            keyring,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opened_envelope,
          decodeErrorData: sse_decode_envelope_error,
        ),
        constMeta: kCrateApiOpenConstMeta,
        argValues: [envelope, keyring],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpenConstMeta =>
      const TaskConstMeta(debugName: "open", argNames: ["envelope", "keyring"]);

  @override
  Uint8List crateApiRewrap({
    required List<int> envelope,
    required List<Audience> audiences,
    required Keyring keyring,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(envelope, serializer);
          sse_encode_list_audience(audiences, serializer);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
            keyring,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_envelope_error,
        ),
        constMeta: kCrateApiRewrapConstMeta,
        argValues: [envelope, audiences, keyring],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRewrapConstMeta => const TaskConstMeta(
    debugName: "rewrap",
    argNames: ["envelope", "audiences", "keyring"],
  );

  @override
  Uint8List crateApiSeal({
    required List<int> payload,
    required ObjectSlot object,
    required List<Audience> audiences,
    required Keyring keyring,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(payload, serializer);
          sse_encode_box_autoadd_object_slot(object, serializer);
          sse_encode_list_audience(audiences, serializer);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
            keyring,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_envelope_error,
        ),
        constMeta: kCrateApiSealConstMeta,
        argValues: [payload, object, audiences, keyring],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSealConstMeta => const TaskConstMeta(
    debugName: "seal",
    argNames: ["payload", "object", "audiences", "keyring"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Keyring => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Keyring => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring;

  @protected
  Keyring
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KeyringImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Keyring
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KeyringImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Keyring
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KeyringImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Keyring
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KeyringImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Audience dco_decode_audience(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Audience(
      group: dco_decode_String(arr[0]),
      epoch: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ObjectSlot dco_decode_box_autoadd_object_slot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_object_slot(raw);
  }

  @protected
  EnvelopeError dco_decode_envelope_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return EnvelopeError(
      kind: dco_decode_envelope_error_kind(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  EnvelopeErrorKind dco_decode_envelope_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EnvelopeErrorKind.values[raw as int];
  }

  @protected
  EnvelopeHeader dco_decode_envelope_header(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return EnvelopeHeader(
      object: dco_decode_object_slot(arr[0]),
      audiences: dco_decode_list_audience(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<Audience> dco_decode_list_audience(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_audience).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  ObjectSlot dco_decode_object_slot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ObjectSlot(
      objectType: dco_decode_String(arr[0]),
      id: dco_decode_String(arr[1]),
      familyId: dco_decode_String(arr[2]),
    );
  }

  @protected
  OpenedEnvelope dco_decode_opened_envelope(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return OpenedEnvelope(
      payload: dco_decode_list_prim_u_8_strict(arr[0]),
      header: dco_decode_envelope_header(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Keyring
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KeyringImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Keyring
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KeyringImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Keyring
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KeyringImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Keyring
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KeyringImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Audience sse_decode_audience(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_group = sse_decode_String(deserializer);
    var var_epoch = sse_decode_u_32(deserializer);
    return Audience(group: var_group, epoch: var_epoch);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ObjectSlot sse_decode_box_autoadd_object_slot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_object_slot(deserializer));
  }

  @protected
  EnvelopeError sse_decode_envelope_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_envelope_error_kind(deserializer);
    var var_message = sse_decode_String(deserializer);
    return EnvelopeError(kind: var_kind, message: var_message);
  }

  @protected
  EnvelopeErrorKind sse_decode_envelope_error_kind(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return EnvelopeErrorKind.values[inner];
  }

  @protected
  EnvelopeHeader sse_decode_envelope_header(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_object = sse_decode_object_slot(deserializer);
    var var_audiences = sse_decode_list_audience(deserializer);
    return EnvelopeHeader(object: var_object, audiences: var_audiences);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<Audience> sse_decode_list_audience(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Audience>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_audience(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  ObjectSlot sse_decode_object_slot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_objectType = sse_decode_String(deserializer);
    var var_id = sse_decode_String(deserializer);
    var var_familyId = sse_decode_String(deserializer);
    return ObjectSlot(
      objectType: var_objectType,
      id: var_id,
      familyId: var_familyId,
    );
  }

  @protected
  OpenedEnvelope sse_decode_opened_envelope(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_payload = sse_decode_list_prim_u_8_strict(deserializer);
    var var_header = sse_decode_envelope_header(deserializer);
    return OpenedEnvelope(payload: var_payload, header: var_header);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    Keyring self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KeyringImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    Keyring self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KeyringImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    Keyring self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KeyringImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKeyring(
    Keyring self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KeyringImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_audience(Audience self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.group, serializer);
    sse_encode_u_32(self.epoch, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_object_slot(
    ObjectSlot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_object_slot(self, serializer);
  }

  @protected
  void sse_encode_envelope_error(EnvelopeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_envelope_error_kind(self.kind, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_envelope_error_kind(
    EnvelopeErrorKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_envelope_header(
    EnvelopeHeader self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_object_slot(self.object, serializer);
    sse_encode_list_audience(self.audiences, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_audience(List<Audience> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_audience(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_object_slot(ObjectSlot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.objectType, serializer);
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.familyId, serializer);
  }

  @protected
  void sse_encode_opened_envelope(
    OpenedEnvelope self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.payload, serializer);
    sse_encode_envelope_header(self.header, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class KeyringImpl extends RustOpaque implements Keyring {
  // Not to be used by end users
  KeyringImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  KeyringImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Keyring,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Keyring,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_KeyringPtr,
  );

  bool contains({required String group, required int epoch}) => RustLib
      .instance
      .api
      .crateApiKeyringContains(that: this, group: group, epoch: epoch);

  /// The raw key, for writing to platform secure storage.
  Uint8List exportKey({required String group, required int epoch}) => RustLib
      .instance
      .api
      .crateApiKeyringExportKey(that: this, group: group, epoch: epoch);

  /// Creates a fresh random key for [group] at [epoch], replacing any held.
  void generate({required String group, required int epoch}) => RustLib
      .instance
      .api
      .crateApiKeyringGenerate(that: this, group: group, epoch: epoch);

  /// Restores a key read back from platform secure storage.
  void importKey({
    required String group,
    required int epoch,
    required List<int> key,
  }) => RustLib.instance.api.crateApiKeyringImportKey(
    that: this,
    group: group,
    epoch: epoch,
    key: key,
  );
}
