"""Writes the worked examples into the app's on-device crypto test.

    python3 generate_dart_vectors.py

Run after changing any of the *-v1.json vectors.
"""
import json
from pathlib import Path

here = Path(__file__).parent
target = here / '../../../../apps/family/integration_test/crypto_vectors.dart'

env = json.loads((here / 'envelope-v1.json').read_text())
gr = json.loads((here / 'grant-v1.json').read_text())
pa = json.loads((here / 'pairing-v1.json').read_text())
assert gr['gck'] == env['gck'], 'the two vectors must share their group key'
assert (pa['admitter_device'], pa['new_device']) == (gr['from_device'], gr['to_device'])


def lit(h):
    return '\n'.join(f"    '{h[i:i + 64]}'" for i in range(0, len(h), 64))


target.write_text(f"""// GENERATED by packages/crypto/rust/test-vectors/generate_dart_vectors.py
// from the JSON beside it; regenerate rather than edit. The worked examples of
// crypto design doc §2.1, §3.1, §4.1 and §7.1, for running on a device.

const recipientSecret =
{lit(gr['recipient_secret'])};

const granterSigningPublic =
{lit(gr['granter_signing_public'])};

const grantFamily = '{gr['family_id']}';
const grantFrom = '{gr['from_device']}';
const grantTo = '{gr['to_device']}';

const grant =
{lit(gr['grant'])};

/// The group key the grant delivers, which also opens [envelope].
const gck =
{lit(gr['gck'])};

const envelope =
{lit(env['envelope'])};

const envelopePayload =
{lit(env['payload'])};

/// The child's tablet pairing, before it receives [grant].
const pairingCode = '{pa['code']}';

const endorsement =
{lit(pa['endorsement'])};
""")
print(f'wrote {target.resolve()}')
